name: Run Python script and upload ACF files

on:
  workflow_dispatch:
  repository_dispatch:
    types: [triggered-from-sync-repo]

jobs:
  run-script:
    strategy:
        matrix:
          group: [0, 1, 2]
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        repository: 'xxTree/ManifestAutoUpdate'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests vdf PyGithub

    - name: Create required directories
      run: |
        mkdir -p debug/steamcmd/installed
        mkdir -p debug/steamcmd/downloads

    - name: Download and extract SteamCMD
      run: |
        curl -o debug/steamcmd/downloads/steamcmd_linux.tar.gz https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
        tar -xvf debug/steamcmd/downloads/steamcmd_linux.tar.gz -C debug/steamcmd/installed

    - name: Run Python script
      run: python acf.py
      env:
        KEY: ${{ secrets.TOKEN }}

    - name: Trigger second workflow
      run: |
        curl -XPOST -u "XliOK:${{ secrets.AUTO }}" \
        -H "Accept: application/vnd.github.everest-preview+json" \
        https://api.github.com/repos/XliOK/test/dispatches \
        -d '{"event_type": "run_second_workflow"}'
