name: Upload to Aliyun OSS

on:
  workflow_dispatch:

jobs:
  upload-to-oss:
    strategy:
      matrix:
        num_jobs: 20
        job_index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout target repository
      uses: actions/checkout@v2
      with:
        repository: xxTree/ManifestAutoUpdate
        fetch-depth: 0

    - name: Setup ossutil
      run: |
        wget https://gosspublic.alicdn.com/ossutil/1.7.7/ossutil64
        chmod +x ossutil64
        sudo mv ossutil64 /usr/local/bin/ossutil

    - name: Upload to Aliyun OSS
      run: |
        ossutil config -e oss-cn-beijing.aliyuncs.com -i ${{ secrets.ALIID }} -k ${{ secrets.ALIKEY }}
        
        branches=($(git branch -a | grep -E 'remotes/origin/[0-9]+$' | sed 's/remotes\/origin\///'))
        total_branches=${#branches[@]}
        branches_per_job=$(( (total_branches + num_jobs - 1) / num_jobs ))
        start_index=$(( job_index * branches_per_job ))
        end_index=$(( start_index + branches_per_job - 1 ))

        for i in $(seq $start_index $end_index); do
          if [ $i -lt $total_branches ]; then
            branch=${branches[$i]}
            git checkout $branch
            ossutil cp -r ./ oss://zqb-client/zqb/branches/195270/$branch -f
            echo "Uploaded branch $branch to Aliyun OSS: zqb/branches/195270/$branch"
          fi
        done
      env:
        num_jobs: ${{ matrix.num_jobs }}
        job_index: ${{ matrix.job_index }}
