name: Upload to Aliyun OSS

on:
  workflow_dispatch:

jobs:
  fetch_branches:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: xxTree/ManifestAutoUpdate
        ref: main

    - name: Set matrix for parallel jobs
      id: set-matrix
      run: |
        branches=$(git branch -r | grep -oP '\d+' | jq -R . | jq -s .)
        chunks=$(echo $branches | jq -c '[(. | length / 20 | ceil) as $n | range(0; $n) as $i | .[($i*$n):($i*$n+$n)]] | add')
        chunk_array=$(echo $chunks | jq -c 'join(",")' | sed 's/^/[/;s/$/]/')
        echo "::set-output name=matrix::$chunk_array"

  upload_to_oss:
    needs: fetch_branches
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chunk: ${{fromJson(needs.fetch_branches.outputs.matrix)}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: xxTree/ManifestAutoUpdate
        fetch-depth: 0

    - name: Setup OSSUtil
      run: |
        curl -O https://gosspublic.alicdn.com/ossutil/1.7.7/ossutil64
        chmod 755 ossutil64
        sudo mv ossutil64 /usr/local/bin/ossutil

    - name: Configure OSSUtil
      run: ossutil config -e oss-cn-beijing.aliyuncs.com -i ${{ secrets.ALIID }} -k ${{ secrets.ALIKEY }} -L CH

    - name: Upload to OSS
      run: |
        for branch in $(echo '${{matrix.chunk}}' | jq -r '.[]'); do
          git checkout $branch
          ossutil cp -rf . oss://zqb-client/zqb/branches/$branch --exclude ".git/*"
        done
