name: Upload to Aliyun OSS

on:
  workflow_dispatch:

jobs:
  upload-to-oss:
    strategy:
      matrix:
        group: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout target repository
      uses: actions/checkout@v2
      with:
        repository: xxTree/ManifestAutoUpdate
        fetch-depth: 0

    - name: Setup ossutil
      run: |
        wget https://gosspublic.alicdn.com/ossutil/1.7.7/ossutil64
        chmod +x ossutil64
        sudo mv ossutil64 /usr/local/bin/ossutil

    - name: Upload to Aliyun OSS
      run: |
        ossutil config -e oss-cn-beijing.aliyuncs.com -i ${{ secrets.ALIID }} -k ${{ secrets.ALIKEY }}
        
        branches=($(git branch -a | grep -E 'remotes/origin/[0-9]+$' | sed 's/remotes\/origin\///'))
        total_branches=${#branches[@]}
        branches_per_group=$(( (total_branches + 19) / 20 ))

        for branch in "${branches[@]}"; do
          if (( (branch % 20) + 1 == group )); then
            if git cat-file -e origin/$branch^{commit}; then
              git checkout $branch
              ossutil cp -r --exclude ".git/*" ./ oss://zqb-client/zqb/branches/195270/$branch -f
              echo "Uploaded branch $branch to Aliyun OSS: zqb/branches/195270/$branch"
            else
              echo "Branch $branch does not reference a valid commit, skipping."
            fi
          fi
        done
      env:
        group: ${{ matrix.group }}
