name: Upload to Aliyun OSS

on:
  workflow_dispatch:

jobs:
  prepare_jobs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Get branches
      id: set_matrix
      run: |
        import json
        from subprocess import check_output

        branches = check_output(['git', 'branch', '-a']).decode('utf-8').split('\n')
        numeric_branches = []

        for branch in branches:
          branch = branch.replace('*', '').strip()
          if not branch.startswith('remotes/origin/'):
            continue
          branch = branch.replace('remotes/origin/', '')
          if branch.isnumeric():
            numeric_branches.append(branch)

        print(f'::set-output name=matrix::{json.dumps({"branch": numeric_branches})}')

  upload_to_oss:
    needs: prepare_jobs
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.prepare_jobs.outputs.matrix)}}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branch }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install oss2

    - name: Upload files to OSS
      run: |
        import os
        import oss2
        from pathlib import Path

        # Setup Aliyun OSS
        auth = oss2.Auth(os.environ['ALIID'], os.environ['ALIKEY'])
        bucket = oss2.Bucket(auth, 'oss-cn-beijing.aliyuncs.com', 'zqb-client')

        # Upload the files to OSS
        for root, dirs, files in os.walk('.'):
          for file in files:
            filepath = os.path.join(root, file)
            relative_path = Path(filepath).relative_to('.')
            oss_path = f'zqb/branches/195270/${{ matrix.branch }}/{relative_path}'
            bucket.put_object_from_file(oss_path, filepath)
            print(f'Uploaded {filepath} to {oss_path}')
