name: Update Manifest Data

on:
  schedule:
      - cron: '0 10 * * *' # 设置定时任务，每天凌晨0点运行
  workflow_dispatch:

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install oss2
        pip install PyGithub

    - name: Fetch data and update API
      run: python update_manifest_data.py
      env:
        KEY: ${{ secrets.TOKEN }}
        OSS_ACCESS_KEY_ID: ${{ secrets.ALIID }}
        OSS_ACCESS_KEY_SECRET: ${{ secrets.ALIKEY }}
